version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the path to your Dockerfile if not in the current directory
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.75'
        reservations:
          cpus: '0.5'
    ports:
      - "1313:1313"