version: '3.8'

services:
  web:
    image: class-prediction:latest
    deploy:
      replicas: 3  # Initial number of replicas
      resources:
        limits:
          cpus: '0.75'  # Cutoff at 75% of CPU resources
        reservations:
          cpus: '0.5'   # Initial reservation (50% of CPU resources)
    ports:
      - "1313:1313"
